project:
  type: website

website:
  title: "Grzegorz Orzechowski"
  site-url: "https://gregdynamics.com"
  description: "Associate Professor at LUT University. Multibody dynamics, simulation, and autonomous machinery."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: projects.qmd
        text: Projects
      - href: publications.qmd
        text: Publications
      - href: cv/index.qmd
        text: CV
      - href: events/index.qmd
        text: Events
    right:
      - icon: github
        href: https://github.com/gorzech
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=nqmTFJIAAAAJ
  page-footer:
    left: "© 2026 Grzegorz Orzechowski • LUT University"
    right:
      - text: "Contact"
        href: mailto:grzegorz.orzechowski@lut.fi

format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: _includes/head.html
    toc: false

